-- +goose Up
CREATE TABLE IF NOT EXISTS credit (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , name               TEXT NOT NULL
    , transacted_at      TIMESTAMPTZ NOT NULL
    , amount_in_microsgd BIGINT NOT NULL -- 1 SGD = 1,000,000 micro SGD
    , created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS categories (
    name TEXT PRIMARY KEY
);

-- default set of categories
INSERT INTO categories(name)
VALUES ('Investment')
, ('Insurance')
, ('Parents')
, ('Tax')
, ('Phone')
, ('Education')
, ('Doctor')
, ('Cash')
, ('Train')
, ('Taxi')
, ('Holiday')
, ('Food')
, ('Eating Out')
, ('Groceries')
, ('Shopping - K')
, ('Shopping - J')
, ('Entertainment')
, ('Bag')
, ('Home')
, ('Cleaner')
, ('Gift')
, ('Gifts')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS debit (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , credit_id          BIGINT NOT NULL REFERENCES credit(id)
    , category           TEXT REFERENCES categories(name) -- allow null to give users some time to decide
    , amount_in_microsgd BIGINT NOT NULL -- 1 SGD = 1,000,000 micro SGD
    , created_at         TIMESTAMPTZ DEFAULT NOW()
);
